table D_Funcionarios
	lineageTag: 7d19904e-c930-4b97-8b1c-f251be888bf2

	column Funcionario
		dataType: string
		lineageTag: 939ad581-9320-402b-bf95-04bd25c6c3a9
		summarizeBy: none
		sourceColumn: Funcionario

		annotation SummarizationSetBy = Automatic

	column Cargo
		dataType: string
		lineageTag: 31a2a950-e0a6-4a6c-9b94-8a4808cf4c52
		summarizeBy: none
		sourceColumn: Cargo

		annotation SummarizationSetBy = Automatic

	column Custo_Diario_Funcionario
		dataType: double
		lineageTag: 18cfa208-ac1c-44a5-a61b-e35089f8c93c
		summarizeBy: none
		sourceColumn: Custo_Diario_Funcionario

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Genero
		dataType: string
		lineageTag: f13ddbdb-d86c-4dc1-856f-0baaedebd66a
		summarizeBy: none
		sourceColumn: Genero

		annotation SummarizationSetBy = Automatic

	column Idade
		dataType: double
		formatString: 0
		lineageTag: b70e9406-ee7e-4f92-90c0-d174d70d2114
		summarizeBy: none
		sourceColumn: Idade

		annotation SummarizationSetBy = Automatic

	partition D_Funcionarios = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\ribei\Desktop\Cursos\VsCode\Repositorios\extrato-sos\src\extrato_sos\consolidado\consolidado.xlsx"), null, true),
				    Planilha1_Sheet = Fonte{[Item="Planilha1",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Planilha1_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Data", type date}}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Tipo Alterado", "Categoria_DRE", each if [Tipo Operação] = "Compra" then "(-) DESPESAS OPERACIONAIS GERAIS" else if[Tipo Operação] = "Despesa Operacional" then "(-) DESPESA OPERACIONAL" else if [Tipo Operação] = "Venda" then "(+) FATURAMENTO BRUTO" else if [Tipo Operação] = "Despesa Administrativa" then "(-) DESPESAS ADMINISTRATIVAS" else if [Tipo Operação] = "Investimento" then "(-) INVESTIMENTOS" else if [Tipo Operação] = "Despesa Extra" then "(-) DESPESAS EXTRAS" else if [Tipo Operação] = "Resultado Financeiro" then "(=) RESULTADO FINANCEIRO" else ""),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Coluna Condicional Adicionada",{"Nome da Origem", "Data", "Ano", "Mês", "Funcionario", "Cargo", "Custo Diário Funcionário", "Tipo Operação", "Produto", "Categoria Produto", "Categoria_DRE", "Quantidade", "Preço Unitário", "Valor Total", "Impostos", "Custo", "Cliente", "Fornecedor"}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Colunas Reordenadas",{{"Nome da Origem", "Nome_Origem"}, {"Mês", "Mes"}, {"Custo Diário Funcionário", "Custo_Diario_Funcionario"}, {"Tipo Operação", "Tipo_Operacao"}, {"Categoria Produto", "Categoria_Produto"}, {"Preço Unitário", "Preco_Unitario"}, {"Valor Total", "Valor_Total"}}),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Colunas Renomeadas",{"Funcionario", "Cargo", "Custo_Diario_Funcionario"}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Outras Colunas Removidas", {"Funcionario"}),
				    #"Coluna Condicional Adicionada1" = Table.AddColumn(#"Duplicatas Removidas", "Genero", each if [Funcionario] = "Eduardo Nunes" then "M" else if [Funcionario] = "José Andrade" then "M" else if [Funcionario] = "Pedro Lima" then "M" else "F", type text),
				    #"Coluna Condicional Adicionada2" = Table.AddColumn(#"Coluna Condicional Adicionada1", "Idade", each if [Funcionario] = "Eduardo Nunes" then 34 else if [Funcionario] = "Marina Paiva" then 19 else if [Funcionario] = "José Andrade" then 22 else if [Funcionario] = "Lívia Porto" then 30 else if [Funcionario] = "Pedro Lima" then 41 else if [Funcionario] = "Carla Souza" then 26 else if [Funcionario] = "Amanda Rocha" then 45 else null, type number)
				in
				    #"Coluna Condicional Adicionada2"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

