table Medidas_Func
	lineageTag: 3d22cbbd-50ad-4f0e-b4ff-13bd7bb51e8b

	measure 'Salario Mensal (Dias Uteis)' = ```
			
			VAR DiasUteis =
			    CALCULATE (
			        COUNTROWS ( D_Calendario ),
			        FILTER (
			            D_Calendario,
			            WEEKDAY ( D_Calendario[Date], 2 ) <= 5
			        )
			    )
			RETURN
			    (SUM ( F_Movimentacoes[Custo_Diario_Funcionario] ) + DiasUteis) *-1
			
			```
		lineageTag: 9357b2be-90e7-41b1-a7c9-1085b51734ad

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Salario Mensal (Dias Uteis)2' = ```
			
			VAR DiasUteis =
			    CALCULATE (
			        COUNTROWS ( D_Calendario ),
			        FILTER (
			            D_Calendario,
			            WEEKDAY ( D_Calendario[Date], 2 ) <= 5
			        )
			    )
			RETURN
			    (SUM ( F_Movimentacoes[Custo_Diario_Funcionario] ) + DiasUteis)
			
			```
		lineageTag: d6a503e2-03ad-471f-b7a4-23f43914d31c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Contagem_Homens = CALCULATE(COUNT(D_Funcionarios[Genero]), D_Funcionarios[Genero] = "M")
		formatString: 0
		lineageTag: c2ead807-5935-43d1-96af-74c19a1f67c9

	measure Contagem_Mulheres = CALCULATE(COUNT(D_Funcionarios[Genero]), D_Funcionarios[Genero] = "F")
		formatString: 0
		lineageTag: a746ce68-4a92-4c6c-a5b1-728a08358c4e

	measure Media_salario =
			
			DIVIDE([Salario Mensal (Dias Uteis)2], [Func_Ativos], 0)
		lineageTag: f3066deb-a55f-48cd-9469-4d2222be62aa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Func_Ativos =
			
			SUMX(Medidas_Func, [Contagem_Homens] + [Contagem_Mulheres])
		formatString: 0
		lineageTag: d79a1bbf-534f-44ef-b00f-05b4a0f2c2a2

	measure Media_idade =
			
			AVERAGE(D_Funcionarios[Idade])
		formatString: 0
		lineageTag: 67031cd4-93bb-478a-91dd-bfcbaa66e200

	column Column
		formatString: 0
		lineageTag: 6795a443-a361-4f89-96ed-e00131af76ce
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition Medidas_Func = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 5d15db146c7448988ab07767f346e18e

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

